# Generated by Django 3.2.9 on 2021-11-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knockout_tournament_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='a',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='a',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='b',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='b',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='b',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='c',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='c',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='c',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='d',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='d',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='d',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='e',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='e',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='e',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='f',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='f',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='f',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='g',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='g',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='g',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='h',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='h',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='h',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='i',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='i',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='i',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='j',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='j',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='j',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='k',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='k',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='k',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='l',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='l',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='l',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='m',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='m',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='m',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='n',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='n',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='n',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='o',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='o',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='o',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p',
            name='no_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p',
            name='opp_team_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='p',
            name='tot_matches',
            field=models.IntegerField(default=0),
        ),
    ]
